# Resolves a city name to its main IATA airport code.
# Used when a participant or candidate city doesn't have an explicit airport code.
class AirportResolver
  AIRPORT_CODES = {
    # France
    "paris"        => "CDG",
    "lyon"         => "LYS",
    "marseille"    => "MRS",
    "nice"         => "NCE",
    "toulouse"     => "TLS",
    "bordeaux"     => "BOD",
    "nantes"       => "NTE",
    "strasbourg"   => "SXB",
    "lille"        => "LIL",
    "rennes"       => "RNS",
    "montpellier"  => "MPL",
    "brest"        => "BES",
    "biarritz"     => "BIQ",
    "pau"          => "PUF",
    "perpignan"    => "PGF",
    "clermont-ferrand" => "CFE",
    "clermont"     => "CFE",
    "ajaccio"      => "AJA",
    "bastia"       => "BIA",
    "calvi"        => "CLY",
    "figari"       => "FSC",
    "limoges"      => "LIG",
    "tours"        => "TUF",
    "metz"         => "ETZ",
    "nancy"        => "ENC",
    "beauvais"     => "BVA",
    # UK
    "london"       => "LHR",
    "londres"      => "LHR",
    "manchester"   => "MAN",
    "edinburgh"    => "EDI",
    "édimbourg"    => "EDI",
    "edimbourg"    => "EDI",
    "birmingham"   => "BHX",
    "bristol"      => "BRS",
    "glasgow"      => "GLA",
    "liverpool"    => "LPL",
    "newcastle"    => "NCL",
    "leeds"        => "LBA",
    "aberdeen"     => "ABZ",
    "belfast"      => "BFS",
    "cardiff"      => "CWL",
    "southampton"  => "SOU",
    "exeter"       => "EXT",
    "inverness"    => "INV",
    # Ireland
    "dublin"       => "DUB",
    "cork"         => "ORK",
    "shannon"      => "SNN",
    "knock"        => "NOC",
    # Spain
    "madrid"       => "MAD",
    "barcelona"    => "BCN",
    "barcelone"    => "BCN",
    "valencia"     => "VLC",
    "valence"      => "VLC",
    "seville"      => "SVQ",
    "séville"      => "SVQ",
    "sevilla"      => "SVQ",
    "malaga"       => "AGP",
    "málaga"       => "AGP",
    "bilbao"       => "BIO",
    "alicante"     => "ALC",
    "palma"        => "PMI",
    "ibiza"        => "IBZ",
    "menorca"      => "MAH",
    "mahon"        => "MAH",
    "tenerife"     => "TFS",
    "gran canaria" => "LPA",
    "las palmas"   => "LPA",
    "lanzarote"    => "ACE",
    "fuerteventura" => "FUE",
    "santiago de compostela" => "SCQ",
    "saint-jacques-de-compostelle" => "SCQ",
    "asturias"     => "OVD",
    "oviedo"       => "OVD",
    "santander"    => "SDR",
    "saragosse"    => "ZAZ",
    "zaragoza"     => "ZAZ",
    "girona"       => "GRO",
    "gerone"       => "GRO",
    "murcia"       => "MJV",
    "murcie"       => "MJV",
    "granada"      => "GRX",
    "grenade"      => "GRX",
    # Germany
    "berlin"       => "BER",
    "munich"       => "MUC",
    "münchen"      => "MUC",
    "frankfurt"    => "FRA",
    "francfort"    => "FRA",
    "hamburg"      => "HAM",
    "hambourg"     => "HAM",
    "cologne"      => "CGN",
    "köln"         => "CGN",
    "düsseldorf"   => "DUS",
    "dusseldorf"   => "DUS",
    "stuttgart"    => "STR",
    "hanover"      => "HAJ",
    "hannover"     => "HAJ",
    "hanovre"      => "HAJ",
    "nuremberg"    => "NUE",
    "nürnberg"     => "NUE",
    "leipzig"      => "LEJ",
    "dresden"      => "DRS",
    "dresde"       => "DRS",
    "bremen"       => "BRE",
    "brême"        => "BRE",
    "dortmund"     => "DTM",
    # Italy
    "rome"         => "FCO",
    "roma"         => "FCO",
    "milan"        => "MXP",
    "milano"       => "MXP",
    "naples"       => "NAP",
    "napoli"       => "NAP",
    "venice"       => "VCE",
    "venise"       => "VCE",
    "venezia"      => "VCE",
    "florence"     => "FLR",
    "firenze"      => "FLR",
    "bologna"      => "BLQ",
    "bologne"      => "BLQ",
    "turin"        => "TRN",
    "torino"       => "TRN",
    "pisa"         => "PSA",
    "pise"         => "PSA",
    "bari"         => "BRI",
    "palermo"      => "PMO",
    "palerme"      => "PMO",
    "catania"      => "CTA",
    "catane"       => "CTA",
    "verona"       => "VRN",
    "vérone"       => "VRN",
    "genoa"        => "GOA",
    "gênes"        => "GOA",
    "genova"       => "GOA",
    "cagliari"     => "CAG",
    "olbia"        => "OLB",
    "trieste"      => "TRS",
    # Netherlands
    "amsterdam"    => "AMS",
    "rotterdam"    => "RTM",
    "eindhoven"    => "EIN",
    "groningen"    => "GRQ",
    "maastricht"   => "MST",
    # Belgium
    "brussels"     => "BRU",
    "bruxelles"    => "BRU",
    "antwerp"      => "ANR",
    "anvers"       => "ANR",
    "charleroi"    => "CRL",
    "liege"        => "LGG",
    "liège"        => "LGG",
    "ostend"       => "OST",
    # Luxembourg
    "luxembourg"   => "LUX",
    # Portugal
    "lisbon"       => "LIS",
    "lisbonne"     => "LIS",
    "lisboa"       => "LIS",
    "porto"        => "OPO",
    "faro"         => "FAO",
    "funchal"      => "FNC",
    "madeira"      => "FNC",
    "madere"       => "FNC",
    "ponta delgada" => "PDL",
    "azores"       => "PDL",
    # Switzerland
    "zurich"       => "ZRH",
    "zürich"       => "ZRH",
    "geneva"       => "GVA",
    "genève"       => "GVA",
    "geneve"       => "GVA",
    "basel"        => "BSL",
    "bâle"         => "BSL",
    "bern"         => "BRN",
    "berne"        => "BRN",
    "lugano"       => "LUG",
    # Austria
    "vienna"       => "VIE",
    "vienne"       => "VIE",
    "wien"         => "VIE",
    "salzburg"     => "SZG",
    "salzbourg"    => "SZG",
    "innsbruck"    => "INN",
    "graz"         => "GRZ",
    "linz"         => "LNZ",
    # Denmark
    "copenhagen"   => "CPH",
    "copenhague"   => "CPH",
    "københavn"    => "CPH",
    "billund"      => "BLL",
    "aarhus"       => "AAR",
    # Sweden
    "stockholm"    => "ARN",
    "gothenburg"   => "GOT",
    "göteborg"     => "GOT",
    "malmo"        => "MMX",
    "malmö"        => "MMX",
    # Norway
    "oslo"         => "OSL",
    "bergen"       => "BGO",
    "trondheim"    => "TRD",
    "stavanger"    => "SVG",
    "tromso"       => "TOS",
    "tromsø"       => "TOS",
    # Finland
    "helsinki"     => "HEL",
    "tampere"      => "TMP",
    "turku"        => "TKU",
    "rovaniemi"    => "RVN",
    # Iceland
    "reykjavik"    => "KEF",
    "reykjavík"    => "KEF",
    # Poland
    "warsaw"       => "WAW",
    "varsovie"     => "WAW",
    "warszawa"     => "WAW",
    "krakow"       => "KRK",
    "cracovie"     => "KRK",
    "kraków"       => "KRK",
    "gdansk"       => "GDN",
    "gdańsk"       => "GDN",
    "wroclaw"      => "WRO",
    "wrocław"      => "WRO",
    "poznan"       => "POZ",
    "poznań"       => "POZ",
    "katowice"     => "KTW",
    # Czech Republic
    "prague"       => "PRG",
    "praha"        => "PRG",
    "brno"         => "BRQ",
    # Slovakia
    "bratislava"   => "BTS",
    "kosice"       => "KSC",
    "košice"       => "KSC",
    # Hungary
    "budapest"     => "BUD",
    "debrecen"     => "DEB",
    # Greece
    "athens"       => "ATH",
    "athènes"      => "ATH",
    "thessaloniki" => "SKG",
    "thessalonique" => "SKG",
    "heraklion"    => "HER",
    "héraklion"    => "HER",
    "rhodes"       => "RHO",
    "santorini"    => "JTR",
    "santorin"     => "JTR",
    "mykonos"      => "JMK",
    "corfu"        => "CFU",
    "corfou"       => "CFU",
    "kos"          => "KGS",
    # Romania
    "bucharest"    => "OTP",
    "bucarest"     => "OTP",
    "cluj"         => "CLJ",
    "cluj-napoca"  => "CLJ",
    "timisoara"    => "TSR",
    "timișoara"    => "TSR",
    "iasi"         => "IAS",
    "iași"         => "IAS",
    # Bulgaria
    "sofia"        => "SOF",
    "varna"        => "VAR",
    "burgas"       => "BOJ",
    # Croatia
    "zagreb"       => "ZAG",
    "split"        => "SPU",
    "dubrovnik"    => "DBV",
    "pula"         => "PUY",
    "zadar"        => "ZAD",
    "rijeka"       => "RJK",
    # Slovenia
    "ljubljana"    => "LJU",
    # Serbia
    "belgrade"     => "BEG",
    "nis"          => "INI",
    # Bosnia and Herzegovina
    "sarajevo"     => "SJJ",
    # Montenegro
    "podgorica"    => "TGD",
    "tivat"        => "TIV",
    # North Macedonia
    "skopje"       => "SKP",
    # Albania
    "tirana"       => "TIA",
    # Kosovo
    "pristina"     => "PRN",
    "priština"     => "PRN",
    # Lithuania
    "vilnius"      => "VNO",
    "kaunas"       => "KUN",
    # Latvia
    "riga"         => "RIX",
    # Estonia
    "tallinn"      => "TLL",
    # Belarus
    "minsk"        => "MSQ",
    # Ukraine
    "kyiv"         => "KBP",
    "kiev"         => "KBP",
    "lviv"         => "LWO",
    "odesa"        => "ODS",
    "odessa"       => "ODS",
    # Moldova
    "chisinau"     => "KIV",
    "chișinău"     => "KIV",
    # Russia (European part)
    "moscow"       => "SVO",
    "moscou"       => "SVO",
    "saint petersburg" => "LED",
    "saint-pétersbourg" => "LED",
    "st petersburg" => "LED",
    # Turkey (European hub)
    "istanbul"     => "IST",
    "ankara"       => "ESB",
    "izmir"        => "ADB",
    "antalya"      => "AYT",
    # Cyprus
    "larnaca"      => "LCA",
    "paphos"       => "PFO",
    "nicosia"      => "LCA",
    # Malta
    "malta"        => "MLA",
    "malte"        => "MLA",
    "valletta"     => "MLA",
    "la valette"   => "MLA",
  }.freeze

  def self.call(city_name)
    normalized = city_name.to_s.downcase.strip
    AIRPORT_CODES[normalized] || fallback(city_name)
  end

  private

  def self.fallback(city_name)
    city_name.to_s.upcase.gsub(/[^A-Z]/, "")[0..2]
  end
end
